# Generated by Django 5.0 on 2023-12-12 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.CharField(max_length=500, null=True, verbose_name='Description'),
        ),
    ]
