# Generated by Django 3.2.6 on 2023-12-18 23:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup',
            name='ticket',
        ),
        migrations.AddField(
            model_name='followup',
            name='ticket_uid',
            field=models.CharField(max_length=36, null=True, verbose_name='Ticket_uid'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='product_uid',
            field=models.CharField(max_length=36, null=True, verbose_name='Product_Uid'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='uid',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True, verbose_name='Uid'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pre_set_reply',
            field=models.CharField(max_length=200, null=True, verbose_name='Pre Set Reply'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.CharField(default=uuid.uuid4, max_length=36, unique=True, verbose_name='Uid'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='owner',
            field=models.CharField(blank=True, max_length=36, verbose_name='Owner user uid'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('owner', 'name')},
        ),
        migrations.DeleteModel(
            name='PreSetReply',
        ),
    ]
