# Generated by Django 3.2.6 on 2023-12-14 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='Address',
            new_name='address',
        ),
    ]
