# Generated by Django 3.2.6 on 2023-12-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20231218_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_agent',
            field=models.BooleanField(default=False, verbose_name='is Agent'),
        ),
    ]
