# Generated by Django 3.2.6 on 2024-01-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20231219_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='dead_line_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='user',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.CharField(max_length=36, verbose_name='Organization Name'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='owner',
            field=models.CharField(blank=True, max_length=36, verbose_name='Owner username'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Reopened', 'Reopened'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], max_length=50, null=True, verbose_name='Status'),
        ),
    ]
